name: BACKUP

on:
  workflow_dispatch:
  schedule:
    - cron: '* */1 * * *'
jobs:
  Build:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - {
              type: "32bit",
              id: "1",
            }
          - {
              type: "64bit",
              id: "2",
            }

    steps:
      - uses: actions/checkout@v3

      - name: Downloading lib
        if: ${{ matrix.job.type=='32bit' }}
        run: |
          bash knmod32

      - name: Delete tag if exists
        if: ${{ matrix.job.type=='32bit' }}
        uses: JeelsBoobz/delete-tag-and-release@latest
        with:
          delete_release: true
          tag_name: MLBB-KNMOD-External-32bit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        if: ${{ matrix.job.type=='32bit' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: MLBB-KNMOD-External-32bit
          files: lib32/*
          generate_release_notes: true

      - name: Downloading lib
        if: ${{ matrix.job.type=='64bit' }}
        run: |
          bash knmod64

      - name: Delete tag if exists
        if: ${{ matrix.job.type=='64bit' }}
        uses: JeelsBoobz/delete-tag-and-release@latest
        with:
          delete_release: true
          tag_name: MLBB-KNMOD-External-64bit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        if: ${{ matrix.job.type=='64bit' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: MLBB-KNMOD-External-64bit
          files: lib64/*
          generate_release_notes: true
