name: Mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
jobs:

  Mirror:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - {
              id: "1",
              target: "knmod",
              type: "vip",
            }
          - {
              id: "2",
              target: "fakecez",
              type: "vip",
            }
          - {
              id: "3",
              target: "senju",
              type: "vip",
            }
          - {
              id: "4",
              target: "novuz",
              type: "vip",
            }

    steps:
      - uses: actions/checkout@v4

      - name: Downloading KNMOD VIP
        if: ${{ matrix.job.target=='knmod' && matrix.job.type=='vip' }}
        run: |
          mkdir KNMODVIP
          cd KNMODVIP
          URL="https://knmod.com/file_kn/lib/knnew.zip"
          bash ../download $(basename ${URL}) ${URL}

      - name: Delete tag if exists
        if: ${{ success() && matrix.job.target=='knmod' && matrix.job.type=='vip' }}
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: MLBB-KNMOD-VIP
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        id: release_knmod_vip
        if: ${{ success() && matrix.job.target=='knmod' && matrix.job.type=='vip' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: MLBB-KNMOD-VIP
          files: KNMODVIP/*
          draft: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        if: ${{ success() && matrix.job.target=='knmod' && matrix.job.type=='vip' }}
        uses: StuYarrow/publish-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.release_knmod_vip.outputs.id }}

      - name: Downloading Fakecez VIP
        if: ${{ matrix.job.target=='fakecez' && matrix.job.type=='vip' }}
        run: |
          mkdir FakecezVIP
          cd FakecezVIP
          URL="https://fakecez.com/VIPPROJECT/Fakecez/exfile.zip"
          bash ../download $(basename ${URL}) ${URL}

      - name: Delete tag if exists
        if: ${{ success() && matrix.job.target=='fakecez' && matrix.job.type=='vip' }}
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: MLBB-FAKECEZ-VIP
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        id: release_fakecez_vip
        if: ${{ success() && matrix.job.target=='fakecez' && matrix.job.type=='vip' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: MLBB-FAKECEZ-VIP
          files: FakecezVIP/*
          draft: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        if: ${{ success() && matrix.job.target=='fakecez' && matrix.job.type=='vip' }}
        uses: StuYarrow/publish-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.release_fakecez_vip.outputs.id }}

      - name: Downloading Senju VIP
        if: ${{ matrix.job.target=='senju' && matrix.job.type=='vip' }}
        run: |
          mkdir SenjuVIP
          cd SenjuVIP
          URL="https://fakecez.com/VIPPROJECT/Senju/exfile.zip"
          bash ../download $(basename ${URL}) ${URL}

      - name: Delete tag if exists
        if: ${{ success() && matrix.job.target=='senju' && matrix.job.type=='vip' }}
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: MLBB-SENJU-VIP
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        id: release_senju_vip
        if: ${{ success() && matrix.job.target=='senju' && matrix.job.type=='vip' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: MLBB-SENJU-VIP
          files: SenjuVIP/*
          draft: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        if: ${{ success() && matrix.job.target=='senju' && matrix.job.type=='vip' }}
        uses: StuYarrow/publish-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.release_senju_vip.outputs.id }}

      - name: Downloading Novuz VIP
        if: ${{ matrix.job.target=='novuz' && matrix.job.type=='vip' }}
        run: |
          mkdir NovuzVIP
          cd NovuzVIP
          URL="https://fakecez.com/VIPPROJECT/Novuz/exfile.zip"
          bash ../download $(basename ${URL}) ${URL}

      - name: Delete tag if exists
        if: ${{ success() && matrix.job.target=='novuz' && matrix.job.type=='vip' }}
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: MLBB-NOVUZ-VIP
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        id: release_novuz_vip
        if: ${{ success() && matrix.job.target=='novuz' && matrix.job.type=='vip' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: MLBB-NOVUZ-VIP
          files: NovuzVIP/*
          draft: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        if: ${{ success() && matrix.job.target=='novuz' && matrix.job.type=='vip' }}
        uses: StuYarrow/publish-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.release_novuz_vip.outputs.id }}
