name: Mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
jobs:
  Mirror:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Downloading MLBB-KNMOD-External-32bit
        run: |
          cd /home/runner/work/Mirror-KuroNew/Mirror-KuroNew
          mkdir knmod32
          cd knmod32
          URL="https://knmod.com/file_kn/lib/armeabi-v7a/libAkSoundEngine.bytes"
          bash ../download $(basename ${URL}) ${URL}

      - name: Delete tag MLBB-KNMOD-External-32bit if exists
        uses: JeelsBoobz/delete-tag-and-release@latest
        with:
          delete_release: true
          tag_name: MLBB-KNMOD-External-32bit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release MLBB-KNMOD-External-32bit
        uses: softprops/action-gh-release@v1
        with:
          tag_name: MLBB-KNMOD-External-32bit
          files: knmod32/*
          generate_release_notes: true

      - name: Downloading MLBB-KNMOD-External-64bit
        run: |
          cd /home/runner/work/Mirror-KuroNew/Mirror-KuroNew
          mkdir knmod64
          cd knmod64
          URL="https://knmod.com/file_kn/lib/arm64-v8a/libAkSoundEngine.bytes"
          bash ../download $(basename ${URL}) ${URL}

      - name: Delete tag MLBB-KNMOD-External-64bit if exists
        uses: JeelsBoobz/delete-tag-and-release@latest
        with:
          delete_release: true
          tag_name: MLBB-KNMOD-External-64bit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release MLBB-KNMOD-External-64bit
        uses: softprops/action-gh-release@v1
        with:
          tag_name: MLBB-KNMOD-External-64bit
          files: knmod64/*
          generate_release_notes: true

      - name: Downloading MLBB-VIPROCK-External-32bit
        run: |
          cd /home/runner/work/Mirror-KuroNew/Mirror-KuroNew
          mkdir viprock32
          cd viprock32
          URL="https://viprock.my.id/file_rock/lib/armeabi-v7a/libAkSoundEngine.bytes"
          bash ../download $(basename ${URL}) ${URL}

      - name: Delete tag MLBB-VIPROCK-External-32bit if exists
        uses: JeelsBoobz/delete-tag-and-release@latest
        with:
          delete_release: true
          tag_name: MLBB-VIPROCK-External-32bit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release MLBB-VIPROCK-External-32bit
        uses: softprops/action-gh-release@v1
        with:
          tag_name: MLBB-VIPROCK-External-32bit
          files: viprock32/*
          generate_release_notes: true

      - name: Downloading MLBB-VIPROCK-External-64bit
        run: |
          cd /home/runner/work/Mirror-KuroNew/Mirror-KuroNew
          mkdir viprock64
          cd viprock64
          URL="https://viprock.my.id/file_rock/lib/arm64-v8a/libAkSoundEngine.bytes"
          bash ../download $(basename ${URL}) ${URL}

      - name: Delete tag MLBB-VIPROCK-External-64bit if exists
        uses: JeelsBoobz/delete-tag-and-release@latest
        with:
          delete_release: true
          tag_name: MLBB-VIPROCK-External-64bit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release MLBB-VIPROCK-External-64bit
        uses: softprops/action-gh-release@v1
        with:
          tag_name: MLBB-VIPROCK-External-64bit
          files: viprock64/*
          generate_release_notes: true

      - name: Downloading MLBB-KNMOD-Internal
        run: |
          cd /home/runner/work/Mirror-KuroNew/Mirror-KuroNew
          mkdir knmodapk
          cd knmodapk
          URL=$(curl -s -X POST https://knmod.com/file_kn/knapkmod | grep ".apk'>" | sed "s/.*<a href='\(.*\)'>.*/\1/")
          bash ../download $(basename ${URL}) ${URL}

      - name: Delete tag MLBB-KNMOD-Internal if exists
        uses: JeelsBoobz/delete-tag-and-release@latest
        with:
          delete_release: true
          tag_name: MLBB-KNMOD-Internal
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release MLBB-KNMOD-Internal
        uses: softprops/action-gh-release@v1
        with:
          tag_name: MLBB-KNMOD-Internal
          files: knmodapk/*
          generate_release_notes: true

      - name: Downloading AOV-GARENA-KNMOD
        run: |
          cd /home/runner/work/Mirror-KuroNew/Mirror-KuroNew
          mkdir knmod-aov-garena
          cd knmod-aov-garena
          URL=$(curl -s -X POST https://knmod.com/file_kn/knmodaovgarena | grep ".apk'>" | sed "s/.*<a href='\(.*\)'>.*/\1/")
          bash ../download $(basename ${URL}) ${URL}

      - name: Delete tag AOV-GARENA-KNMOD if exists
        uses: JeelsBoobz/delete-tag-and-release@latest
        with:
          delete_release: true
          tag_name: AOV-GARENA-KNMOD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release AOV-GARENA-KNMOD
        uses: softprops/action-gh-release@v1
        with:
          tag_name: AOV-GARENA-KNMOD
          files: knmod-aov-garena/*
          generate_release_notes: true

      - name: Downloading MLBB-FAKECEZ-VIP
        run: |
          cd /home/runner/work/Mirror-KuroNew/Mirror-KuroNew
          mkdir FakecezVIP
          cd FakecezVIP
          URL="https://vip.fakecez.com/assets.zip"
          bash ../download $(basename ${URL}) ${URL}

      - name: Delete tag MLBB-FAKECEZ-VIP if exists
        uses: JeelsBoobz/delete-tag-and-release@latest
        with:
          delete_release: true
          tag_name: MLBB-FAKECEZ-VIP
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release MLBB-FAKECEZ-VIP
        uses: softprops/action-gh-release@v1
        with:
          tag_name: MLBB-FAKECEZ-VIP
          files: FakecezVIP/*
          generate_release_notes: true

      - name: Delete Draft Releases
        uses: hugo19941994/delete-draft-releases@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
